[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"
  commandOrigin: config
  publish: /opt/build/repo/public
  publishOrigin: config

[build.environment]
  HUGO_VERSION = "0.87.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  origin: config
  [plugins.inputs]
    debug = true
